export const ORDER_CREATE_REQUEST = "ORDER_CREATE_REQUEST";
export const ORDER_CREATE_SUCCESS = "ORDER_CREATE_SUCCESS";
export const ORDER_CREATE_FAIL = "ORDER_CREATE_FAIL";
export const ORDER_CREATE_RESET = "ORDER_CREATE_RESET";

export const ORDER_DETAILS_REQUEST = "ORDER_DETAILS_REQUEST";
export const ORDER_DETAILS_SUCCESS = "ORDER_DETAILS_SUCCESS";
export const ORDER_DETAILS_FAIL = "ORDER_DETAILS_FAIL";

export const ORDER_PAY_REQUEST = "ORDER_PAY_REQUEST";
export const ORDER_PAY_SUCCESS = "ORDER_PAY_SUCCESS";
export const ORDER_PAY_FAIL = "ORDER_PAY_FAIL";
export const ORDER_PAY_RESET = "ORDER_PAY_RESET";

export const USER_ORDERS_LIST_REQUEST = "USER_ORDERS_LIST_REQUEST";
export const USER_ORDERS_LIST_SUCCESS = "USER_ORDERS_LIST_SUCCESS";
export const USER_ORDERS_LIST_FAIL = "USER_ORDERS_LIST_FAIL";
export const USER_ORDERS_LIST_RESET = "USER_ORDERS_LIST_RESET";

export const ORDERS_LIST_REQUEST = "ORDERS_LIST_REQUEST";
export const ORDERS_LIST_SUCCESS = "ORDERS_LIST_SUCCESS";
export const ORDERS_LIST_FAIL = "ORDERS_LIST_FAIL";

export const ORDERS_DELIVER_REQUEST = "ORDERS_DELIVER_REQUEST";
export const ORDERS_DELIVER_SUCCESS = "ORDERS_DELIVER_SUCCESS";
export const ORDERS_DELIVER_FAIL = "ORDERS_DELIVER_FAIL";
export const ORDER_DELIVER_RESET = "ORDER_DELIVER_RESET";
